[package]
name = "leetcode-ihiro"
version = "0.1.0"
edition = "2024"

[[bin]]
name="1"
path="src/1.rs"

[[bin]]
name="9"
path="src/9.rs"

[[bin]]
name="13"
path="src/13.rs"

[[bin]]
name="69"
path="src/69.rs"

[dependencies]
